### ISSUE TITLE
su - amidev does not set correct PATH to cross compiler tools

### ISSUE THREAD

**Issue by josefwegner** [walkero-gr/AmigaGCConDocker#7]
If you switch to the `amidev` user using `su - amidev` (start the shell as a login shell, like a real login), it is missing `/opt/ppc-amigaos/bin` in PATH.

Just using `su amidev` (using root's environment) has the correct PATH.

Maybe we should set the correct PATH in `amidev`'s .profile file.

**Comment by walkero-gr** [comment]
@josefwegner 
I just tested it starting the container like
`docker run -it --rm -u amidev --name os4-gcc11-afxgroupos4-gcc11-afxgroup -v "${PWD}/code":/opt/code -w /opt/code walkero/amigagccondocker:os4-gcc11-afxgroup /bin/bash`
and with `printenv` I see the following path
`PATH=/opt/ppc-amigaos/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
Can you give me more info on how you start it and what do you do?

**Comment by josefwegner** [comment]
These are the steps I did:

```
$ docker run -it --rm --name gcc11-ppc -v ${PWD}:/opt/code -w /opt/code walkero/amigagccondocker:os4-gcc11-afxgroup /bin/bash
root@94eacb4da38d:/opt/code# echo $PATH
/opt/ppc-amigaos/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@94eacb4da38d:/opt/code# su - amidev
amidev@94eacb4da38d:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
amidev@94eacb4da38d:~$ exit
logout
root@94eacb4da38d:/opt/code# exit
exit
```

Using `docker run -u amidev`, or using `su amidev` (without the dash `-` for login shell) in bash seems to work, though.
